# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef2e2d051cdd0fd6bfa5ab4a127ba31d20d25e23d9069087a2597b6040521a0b8f946490198a46268ddb64de3e59a3175c90641f4c139702294e07b0ad6adbe0

test:
  secret_key_base: 089d9e35c4171cab62bd1fe25d7a7e3ec4b0603d9bda0d5184c9ed1b79deb5d2b1f8aa4753adc7bba258afe1121a59f44074cb30dc799b050c3466bd5ab3138c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
